Traceback (most recent call last):
  File "/Users/hernando/opt/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/hernando/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/hernando/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/hernando/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/hernando/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/hernando/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/hernando/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/hernando/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# number of  blind events
n_Bi_total = collpars.n_Bi_total
n_Tl_total = collpars.n_Tl_total

eff_Bi_E   = collpars.eff_Bi_E
eff_Tl_E   = collpars.eff_Tl_E
eff_bb_E   = collpars.eff_bb_E
print('Number of bkg events in full data : Bi = {:6.2f}, Tl = {:6.2f}.'.format(n_Bi_total, n_Tl_total))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m/var/folders/56/_pmdccc97ljb_l3v3s6gkrxm0000gn/T/ipykernel_15183/2112428073.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;31m# number of  blind events[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0mn_Bi_total[0m [0;34m=[0m [0mcollpars[0m[0;34m.[0m[0mn_Bi_total[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      3[0m [0mn_Tl_total[0m [0;34m=[0m [0mcollpars[0m[0;34m.[0m[0mn_Tl_total[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0;34m[0m[0m
[1;32m      5[0m [0meff_Bi_E[0m   [0;34m=[0m [0mcollpars[0m[0;34m.[0m[0meff_Bi_E[0m[0;34m[0m[0;34m[0m[0m

[0;31mAttributeError[0m: module 'collpars' has no attribute 'n_Bi_total'
AttributeError: module 'collpars' has no attribute 'n_Bi_total'

